version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.3.4-node-browsers
         environment:
           RAILS_ENV: test
           PGHOST: 127.0.0.1
           DATABASE_URL: postgres://cahootify_user_ingester@127.0.0.1/cahootify_user_ingester_test
       - image: circleci/postgres:9.6
         environment:
           POSTGRES_USER: cahootify_user_ingester
           POSTGRES_DB: cahootify_user_ingester_test
           POSTGRES_PASSWORD: ""

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:migrate

      # run tests!
      - run:
          name: run tests
          command: |
            bundle exec rspec

