default: &default
  adapter: postgresql
  encoding: unicode
  username: cahootify_user_ingester
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cahootify_user_ingester_development

test:
  <<: *default
  database: cahootify_user_ingester_test

production:
  <<: *default
  database: cahootify_user_ingester_production
  password: <%= ENV['CAHOOTIFY_USER_INGESTER_DATABASE_PASSWORD'] %>
